media:
  input: public/uploads
  output: /uploads

content:
  - name: entries
    label: Articles
    type: collection
    path: src/content/blog
    #filename: '{year}-{month}-{day}-{primary}'
    #filename: '{fields.title}.md' #doesn't work!?
    # filename: '{primary}.md' #this works
    format: yaml-frontmatter
    view:
      primary: title #default
    fields:
      # - name: id
      #   label: ID
      #   type: string
      #   required: true
      - name: date
        label: date
        type: date
        default: '{year}-{month}-{day}'
        options:
          format: yyyy-MM-dd
      - name: title
        label: Title
        type: string
        required: true
      - name: published
        label: Published
        type: boolean
        default: true
      - name: description
        label: Description
        type: string
        required: true
      - name: image
        label: Image
        type: image
      - name: author
        label: Author
        type: string
        required: false
      - name: blocks
        label: Content Blocks
        type: block
        list: true
        blocks:
          - name: hero
            label: Hero Section
            fields:
              - name: heading
                label: Heading
                type: string
                required: true
              - name: subheading
                label: Subheading
                type: string
              - name: image
                label: Image
                type: image
                required: true
          - name: rtecontent
            label: RTE Content
            fields:
              - name: content
                label: Content
                type: object
                required: true
                fields:
                  - name: content
                    label: Content
                    type: rich-text
          - name: card
            label: Card
            fields:
              - name: title
                label: Title
                type: string
                required: true
              - name: description
                label: Description
                type: text
              - name: image
                label: Image
                type: image
          - name: code
            label: Code Block
            fields:
              - name: language
                label: Language
                type: string
                default: javascript
              - name: code
                label: code
                type: code
                options:
                  lintFn: () => []
                  language: javascript
                  format: javascript
          - name: accordion
            label: Accordion
            fields:
              - name: callout
                label: Callout
                type: callout
              - name: useChevron
                label: Use Chevron Variant
                type: boolean
                default: false
              - name: allowMultiple
                label: Allow Multiple Open
                type: boolean
                default: false
              - name: items
                label: Items
                type: object
                list: true
                fields:
                  - name: title
                    label: Title
                    type: string
                    required: true
                  - name: content
                    label: Content
                    type: rich-text
                    required: true
          - name: imageText
            label: ImageText (2 cols)
            fields:
              - name: headline
                label: Headline
                type: string
              - name: text
                label: Text
                type: string
              - name: image
                label: Image
                type: image
                required: true
              - name: reverseImg
                label: Image Last
                type: boolean
                default: false
              - name: linkText
                label: Link Text
                type: string
              - name: linkUrl
                label: Link Url
                type: string
              - name: linkInternal
                label: Link Internal
                type: boolean
                default: false
              - name: linkStyle
                label: Link Style
                type: select
                options:
                  values: [Button, Button2, Link]
                required: true
          - name: youtubeText
            label: Youtube Text (2 cols)
            fields:
              - name: headline
                label: Headline
                type: string
              - name: text
                label: Text
                type: string
              - name: title
                label: Title
                type: string
              - name: youtubeUrl
                label: Youtube Url
                type: string
              - name: ratio
                label: Ratio
                type: select
                options:
                  values: ['16:9', '4:3', '1:1', '21:9']
              - name: reverse
                label: Youtube Last
                type: boolean
                default: false
              - name: linkText
                label: Link Text
                type: string
              - name: linkUrl
                label: Link Url
                type: string
              - name: linkInternal
                label: Link Internal
                type: boolean
                default: false
              - name: linkStyle
                label: Link Style
                type: select
                options:
                  values: [Button, Button2, Link]
                required: true
          - name: youtube
            label: Youtube
            fields:
              - name: headline
                label: Headline
                type: string
              - name: title
                label: Title
                type: string
              - name: youtubeUrl
                label: Youtube Url
                type: string
              - name: ratio
                label: Ratio
                type: select
                options:
                  values: ['16:9', '4:3', '1:1', '21:9']
          - name: link
            label: Button/Link
            fields:
              - name: title
                label: Title
                type: string
              - name: class
                label: Class
                type: string
              - name: linkText
                label: Link Text
                type: string
              - name: linkUrl
                label: Link Url
                type: string
              - name: linkInternal
                label: Link Internal
                type: boolean
                default: false
              - name: showArrow
                label: Show Arrow
                type: boolean
                default: false
              - name: linkStyle
                label: Link Style
                type: select
                options:
                  values: [Button, Button2, Link]
                required: true
  - name: pages
    label: Modular Pages
    type: collection
    path: src/content/pages
    filename: '{primary}.md'
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: published
        label: Published
        type: boolean
        default: true
      - name: navOrder
        label: Navigation Order
        type: number
      - name: description
        label: Description
        type: string
      - name: linkUrl
        label: Link Override (no blocks will be shown)
        type: string
      - name: blocks
        label: Content Blocks
        type: block
        list: true
        blocks:
          - name: hero
            label: Hero Section
            fields:
              - name: heading
                label: Heading
                type: string
                required: true
              - name: subheading
                label: Subheading
                type: string
              - name: image
                label: Image
                type: image
                required: true
          - name: card
            label: Card
            fields:
              - name: title
                label: Title
                type: string
                required: true
              - name: description
                label: Description
                type: text
              - name: image
                label: Image
                type: image
          - name: code
            label: Code Block
            fields:
              - name: language
                label: Language
                type: string
                default: javascript
              - name: code
                label: Code
                type: code
                default: |
                  // Default code snippet
                  function helloWorld() {
                    return "Hello from PagesCMS";
                  }
          - name: pageheader
            label: Page Header
            fields:
              - name: title
                label: Title
                type: string
                required: true
              - name: subtitle
                label: Subtitle
                type: object
                fields:
                  - name: content
                    label: Content
                    type: rich-text
              - name: bgType
                label: Background Type
                type: string
                default: default
                options:
                  default: Default
                  bordered: Bordered
                  filled: Filled
          - name: rtecontent
            label: RTE Content
            fields:
              - name: content
                label: Content
                type: object
                required: true
                fields:
                  - name: content
                    label: Content
                    type: rich-text
          - name: accordion
            label: Accordion
            fields:
              - name: useChevron
                label: Use Chevron Variant
                type: boolean
                default: false
              - name: allowMultiple
                label: Allow Multiple Open
                type: boolean
                default: false
              - name: items
                label: Items
                type: object
                list: true
                fields:
                  - name: title
                    label: Title
                    type: string
                    required: true
                  - name: content
                    label: Content
                    type: rich-text
                    required: true
          - name: news
            label: News List
            fields:
              - name: items
                label: News Items
                type: list
                fields:
                  - name: title
                    label: Title
                    type: string
                    required: true
                  - name: date
                    label: Date
                    type: date
                    required: true
                  - name: type
                    label: Type
                    type: select
                    options:
                      values: [News, Info, Event]
                    required: true
                  - name: description
                    label: Description
                    type: text
                  - name: image
                    label: Image
                    type: image
                    required: false
                  - name: link
                    label: Link
                    type: string
                    required: false
