name: Reproduce and Fix pnpm

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Verify pnpm install
        run: which pnpm && pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Show environment
        run: |
          echo "PATH: $PATH"
          echo "whoami: $(whoami)"
          echo "node version: $(node -v)"
          echo "npm version: $(npm -v)"

      - name: Check if pnpm is installed
        run: |
          echo "Trying to find pnpm..."
          which pnpm || echo "pnpm NOT FOUND"
          pnpm --version || echo "pnpm --version failed"

      - name: Try installing again
        run: |
          npm install -g pnpm
          pnpm --version
